apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rj40uv239-nodejs
  janus-idp.io/tekton: rj40uv239-nodejs
  backstage.io/kubernetes-id: rj40uv239-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rj40uv239-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
